{% set name = "iobrpy" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools
    - wheel

  run:
    - python >=3.9
    - numpy >=1.22
    - pandas >=1.5
    - scipy >=1.9
    - scikit-learn >=1.2
    - statsmodels >=0.13
    - matplotlib >=3.7
    - tqdm >=4.66
    - gseapy >=1.0.6
    - joblib >=1.3
    - multiqc >=1.31
    - fastp
    - star
    - salmon

test:
  commands:
    - iobrpy --help
    - python run_test.py
    - fastp --version
    - STAR  --version
    - salmon --version
    - multiqc --version
  files:
    - run_test.py

about:
  home: https://github.com/IOBR/IOBRpy
  license: MIT
  license_file: LICENSE
  summary: Immuno-Oncology Biological Research using Python (IOBRpy)
