# 导入 workflow 下每个步骤的 main 函数
from iobrpy.workflow.prepare_salmon import prepare_salmon_tpm as prepare_salmon_tpm_main
from iobrpy.workflow.count2tpm import count2tpm as count2tpm_main
from iobrpy.workflow.anno_eset import main as anno_eset_main
from iobrpy.workflow.calculate_sig_score import calculate_sig_score as calculate_sig_score_main
from iobrpy.workflow.cibersort import cibersort as cibersort_main
from iobrpy.workflow.IPS import main as IPS_main
from iobrpy.workflow.estimate import estimate_score as estimate_score_main
from iobrpy.workflow.mcpcounter import MCPcounter_estimate as MCPcounter_estimate_main
from iobrpy.workflow.mcpcounter import preprocess_input as preprocess_input_main
from iobrpy.workflow.quantiseq import main as quantiseq_main
from iobrpy.workflow.epic import main as epic_main
from iobrpy.workflow.deside import main as deside_main
from iobrpy.workflow.tme_cluster import main as tme_cluster_main
from iobrpy.workflow.LR_cal import main as LR_cal_main
from iobrpy.workflow.nmf import main as nmf_main