name: iobrpy
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.9
  - numpy>=1.22
  - pandas>=1.5
  - scipy>=1.9
  - scikit-learn>=1.2
  - statsmodels>=0.13
  - matplotlib>=3.7
  - joblib>=1.3
  - tqdm>=4.66
  - gseapy>=1.0.6
  - salmon>=1.10.3
  - star>=2.7.11b
  - fastp>=0.23.4
  - multiqc>=1.31
  - gzip
  - pip
  - pip:
      - -e .
