project:
  type: book
  output-dir: ../docs

book:
  title: "IOBRpy Book"
  author:
    - name: Haonan Huang
      email: 2905611068@qq.com
    - name: Dongqiang Zeng
      email: interlaken@smu.edu.cn
  repo-url: https://github.com/IOBR/IOBRpy
  repo-actions: [edit, issue]
  repo-branch: main
  repo-subdir: site
  sidebar:
    logo: assets/img/logo.png
  chapters:
    - index.md
    - installation.md
    - build-index.md
    - runall.md
    - workflow.md
    - commands-and-options.md
    - example/examples.md
    - Troubleshooting.md
    - Citation.md
    
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    number-sections: true
    code-copy: true